name: C++ CI RawVector

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Clean and Configure CMake
      run: |
        rm -rf build
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build Project
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Run Google Tests
      run: |
        cd ${{github.workspace}}/build
        ctest --output-on-failure
