name: C++ CI (Build and Test)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build Project
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Run Tests
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ${{github.workspace}}/build/${{matrix.build_type}}/run_tests.exe
        else
          ${{github.workspace}}/build/run_tests
        fi